"""Attribution canary: did the SEEDED fault's own code path execute?

A crash signature says what died; it cannot say that the seeded patch is what fired
— a different bug in the same class can sign the same. Since the harness controls
the injection, the seeded site can report for itself: a patch calls
`QgbFlags.fired("<bug-id>")` (generated by `scripts/build_app.py`) right before the
fault takes effect, and the shim touches

    /data/data/<package>/files/.qgb/fired/<bug-id>

inside the app's private sandbox — one empty file per fault that ran. That makes the
crash's identity known by construction and demotes the stack signature to
corroboration. The rule that keeps this from being an answer key: the marker must
be unreadable by the agent. The sandbox is unreadable to the shell user on a
non-rooted image, and the only door in — `run-as` — is denied to the agent at the
ADB meter (`adb_meter.deny_reason`). Only the harness reads it, after the agent
exits, over its own un-metered adb.

The marker directory is cleared at every staging point that writes the flags file
(`replay.set_flags`, `episode_runner.write_bug_flags`) and before the cold snapshot
is taken, so a marker seen after a pass or an episode was written during it.
"""

from __future__ import annotations

import logging
import re
import shlex

from .device import _adb

logger = logging.getLogger(__name__)

FIRED_DIR = "files/.qgb/fired"

# A marker is a bug id: what the specs allow (`[a-z0-9-]`, plus `_` and `.` for
# apps that use them). Anything else in the listing is an error message, not a marker.
_MARKER_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,120}$")
_ERROR_HINTS = ("No such file", "run-as:", "Permission denied", "not debuggable", "Error")


def parse_fired(text: str) -> list[str]:
    """`ls -1` of the fired directory -> sorted bug ids. Error lines (`run-as: ...`,
    `No such file`) never become markers. Never raises."""
    out: set[str] = set()
    for line in (text or "").splitlines():
        s = line.strip()
        if not s or any(h in s for h in _ERROR_HINTS) or not _MARKER_RE.match(s):
            continue
        out.add(s)
    return sorted(out)


def clear_fired_sh() -> str:
    """The shell fragment that wipes the markers — spliced into the same `run-as`
    command that writes the flags file, so staging never forgets it."""
    return f"rm -rf {FIRED_DIR}"


async def fired_markers(serial: str | None, package: str) -> list[str]:
    """Bug ids whose seeded path reported itself since the markers were last cleared.
    Read via `run-as` (debuggable build); an app that cannot be run-as'd, or one
    with no markers, gives []. Never raises."""
    if not package:
        return []
    inner = f"ls -1 {FIRED_DIR} 2>/dev/null"
    try:
        rc, out = await _adb(serial or "", "shell",
                             f"run-as {shlex.quote(package)} sh -c {shlex.quote(inner)}")
    except Exception:  # noqa: BLE001 — a diagnostic must never take the caller down
        logger.warning("fired_markers: adb failed for %s", package, exc_info=True)
        return []
    return parse_fired(out.decode("utf-8", "replace"))


async def clear_fired(serial: str | None, package: str) -> bool:
    """Wipe the markers (staging). True when the command ran."""
    if not package:
        return False
    try:
        rc, _ = await _adb(serial or "", "shell",
                           f"run-as {shlex.quote(package)} sh -c {shlex.quote(clear_fired_sh())}")
    except Exception:  # noqa: BLE001
        logger.warning("clear_fired: adb failed for %s", package, exc_info=True)
        return False
    return rc == 0
